// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const AdditionalDriver = sequelize.define('additionalDriver', {
    additionalDriverId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    birthdate: {
      type: DataTypes.DATEONLY,
    },
    driverLicenceNumber: {
      type: DataTypes.STRING,
    },
    driverLicenceDate: {
      type: DataTypes.DATEONLY,
    },
    driverLicencePlace: {
      type: DataTypes.STRING,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'additional_driver',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  AdditionalDriver.associate = (models) => {
    AdditionalDriver.belongsTo(models.booking, {
      foreignKey: {
        name: 'bookingIdKey',
        field: 'booking_id',
      },
      targetKey: 'bookingId',
      as: 'booking',
    });
    AdditionalDriver.hasMany(models.attachment, {
      foreignKey: {
        name: 'additionalDriverIdKey',
        field: 'additional_driver_id',
      },
      sourceKey: 'additionalDriverId',
      as: 'additionalDriverAttachments',
    });
  };

  return AdditionalDriver;
};
