// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const AgencyFilter = sequelize.define('agencyFilter', {
    agencyFilterId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    agencyFilterCode: {
      type: DataTypes.STRING,
    },
    agencyFilterLabel: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'agency_filter',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  AgencyFilter.associate = (models) => {
    AgencyFilter.belongsTo(models.application, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'application_id',
      },
      targetKey: 'applicationId',
      as: 'application',
    });
    AgencyFilter.hasMany(models.agencyFilterAgency, {
      foreignKey: {
        name: 'agencyFilterIdKey',
        field: 'agency_filter_id',
      },
      sourceKey: 'agencyFilterId',
      as: 'agencyFilterAgencyFilterAgencies',
    });
    AgencyFilter.hasMany(models.vehicleTypeFilter, {
      foreignKey: {
        name: 'agencyFilterIdKey',
        field: 'agency_filter_id',
      },
      sourceKey: 'agencyFilterId',
      as: 'agencyFilterVehicleTypeFilters',
    });
  };

  return AgencyFilter;
};
