// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const AirlineCompany = sequelize.define('airlineCompany', {
    airlineCompanyId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    label: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    flightNumberPrefix: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'airline_company',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  AirlineCompany.associate = (models) => {
    AirlineCompany.belongsToMany(models.company, {
      through: 'companyAirlineCompany',
      foreignKey: 'airline_company_id',
      otherKey: 'company_id',
      as: 'companyThroughCompanyAirlineCompanies',
    });
    AirlineCompany.hasMany(models.booking, {
      foreignKey: {
        name: 'airlineCompanyIdKey',
        field: 'airline_company_id',
      },
      sourceKey: 'airlineCompanyId',
      as: 'airlineCompanyBookings',
    });
  };

  return AirlineCompany;
};
