// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Attachment = sequelize.define('attachment', {
    attachmentId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    attachmentPath: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    isSendErp: {
      type: DataTypes.INTEGER,
    },
    errorMessage: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'attachment',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Attachment.associate = (models) => {
    Attachment.belongsTo(models.attachmentType, {
      foreignKey: {
        name: 'attachmentTypeIdKey',
        field: 'attachment_type_id',
      },
      targetKey: 'attachmentTypeId',
      as: 'attachmentType',
    });
    Attachment.belongsTo(models.additionalDriver, {
      foreignKey: {
        name: 'additionalDriverIdKey',
        field: 'additional_driver_id',
      },
      targetKey: 'additionalDriverId',
      as: 'additionalDriver',
    });
    Attachment.belongsTo(models.customer, {
      foreignKey: {
        name: 'customerIdKey',
        field: 'customer_id',
      },
      targetKey: 'customerId',
      as: 'customer',
    });
    Attachment.belongsTo(models.booking, {
      foreignKey: {
        name: 'bookingIdKey',
        field: 'booking_id',
      },
      targetKey: 'bookingId',
      as: 'booking',
    });
  };

  return Attachment;
};
