// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const BookingExtra = sequelize.define('bookingExtra', {
    bookingExtraId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    amount: {
      type: DataTypes.DOUBLE,
    },
    quantity: {
      type: DataTypes.INTEGER,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'booking_extra',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  BookingExtra.associate = (models) => {
    BookingExtra.belongsTo(models.bookingAction, {
      foreignKey: {
        name: 'bookingActionIdKey',
        field: 'booking_action_id',
      },
      targetKey: 'bookingActionId',
      as: 'bookingAction',
    });
    BookingExtra.belongsTo(models.extra, {
      foreignKey: {
        name: 'extraIdKey',
        field: 'extra_id',
      },
      targetKey: 'extraId',
      as: 'extra',
    });
    BookingExtra.belongsTo(models.booking, {
      foreignKey: {
        name: 'bookingIdKey',
        field: 'booking_id',
      },
      targetKey: 'bookingId',
      as: 'booking',
    });
    BookingExtra.belongsToMany(models.extra, {
      through: 'bookingLinkedExtra',
      foreignKey: 'booking_extra_id',
      otherKey: 'extra_id',
      as: 'extraThroughBookingLinkedExtras',
    });
  };

  return BookingExtra;
};
