// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CompanyCountry = sequelize.define('companyCountry', {
    companyId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    countryId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'company_country',
    underscored: true,
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  CompanyCountry.associate = (models) => {
    CompanyCountry.belongsTo(models.company, {
      foreignKey: {
        name: 'companyIdKey',
        field: 'company_id',
      },
      targetKey: 'companyId',
      as: 'company',
    });
    CompanyCountry.belongsTo(models.country, {
      foreignKey: {
        name: 'countryIdKey',
        field: 'country_id',
      },
      targetKey: 'countryId',
      as: 'country',
    });
  };

  return CompanyCountry;
};
