// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const ExtraMedia = sequelize.define('extraMedia', {
    extraId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    mediaId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'extra_media',
    underscored: true,
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  ExtraMedia.associate = (models) => {
    ExtraMedia.belongsTo(models.media, {
      foreignKey: {
        name: 'mediaIdKey',
        field: 'media_id',
      },
      targetKey: 'mediaId',
      as: 'media',
    });
    ExtraMedia.belongsTo(models.extra, {
      foreignKey: {
        name: 'extraIdKey',
        field: 'extra_id',
      },
      targetKey: 'extraId',
      as: 'extra',
    });
  };

  return ExtraMedia;
};
