// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const ExtraType = sequelize.define('extraType', {
    extraTypeId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    extraTypeLabel: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'extra_type',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  ExtraType.associate = (models) => {
    ExtraType.belongsToMany(models.agency, {
      through: 'extraTypeAgency',
      foreignKey: 'extra_type_id',
      otherKey: 'agency_id',
      as: 'agencyThroughExtraTypeAgencies',
    });
    ExtraType.hasMany(models.extra, {
      foreignKey: {
        name: 'extraTypeIdKey',
        field: 'extra_type_id',
      },
      sourceKey: 'extraTypeId',
      as: 'extraTypeExtras',
    });
    ExtraType.hasMany(models.groupExtra, {
      foreignKey: {
        name: 'extraTypeIdKey',
        field: 'extra_type_id',
      },
      sourceKey: 'extraTypeId',
      as: 'extraTypeGroupExtras',
    });
    ExtraType.hasMany(models.workflowTask, {
      foreignKey: {
        name: 'extraTypeIdKey',
        field: 'extra_type_id',
      },
      sourceKey: 'extraTypeId',
      as: 'extraTypeWorkflowTasks',
    });
  };

  return ExtraType;
};
