// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const ExtraDetail = sequelize.define('extraDetail', {
    extraDetailId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    displayDetail: {
      type: DataTypes.INTEGER,
    },
    displayOrder: {
      type: DataTypes.INTEGER,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
  }, {
    tableName: 'extra_detail',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  ExtraDetail.associate = (models) => {
    ExtraDetail.belongsTo(models.groupExtra, {
      foreignKey: {
        name: 'groupExtraIdKey',
        field: 'group_extra_id',
      },
      targetKey: 'groupExtraId',
      as: 'groupExtra',
    });
    ExtraDetail.belongsTo(models.media, {
      foreignKey: {
        name: 'mediaIdKey',
        field: 'media_id',
      },
      targetKey: 'mediaId',
      as: 'media',
    });
    ExtraDetail.belongsToMany(models.extra, {
      through: 'extraDetailExtra',
      foreignKey: 'extra_detail_id',
      otherKey: 'extra_id',
      as: 'extraThroughExtraDetailExtras',
    });
    ExtraDetail.hasMany(models.extraDetailTranslation, {
      foreignKey: {
        name: 'extraDetailIdKey',
        field: 'extra_detail_id',
      },
      sourceKey: 'extraDetailId',
      as: 'extraDetailExtraDetailTranslations',
    });
  };

  return ExtraDetail;
};
