// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const FeaturedVehicle = sequelize.define('featuredVehicle', {
    featuredVehicleId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    dateStart: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
      allowNull: false,
    },
    dateEnd: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    displayOrder: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'featured_vehicle',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  FeaturedVehicle.associate = (models) => {
    FeaturedVehicle.belongsTo(models.vehicle, {
      foreignKey: {
        name: 'vehicleIdKey',
        field: 'vehicle_id',
      },
      targetKey: 'vehicleId',
      as: 'vehicle',
    });
  };

  return FeaturedVehicle;
};
