// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const FeaturedExtra = sequelize.define('featuredExtra', {
    featuredExtraId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    dateStart: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
      allowNull: false,
    },
    dateEnd: {
      type: DataTypes.DATE,
    },
    displayOrder: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'featured_extra',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  FeaturedExtra.associate = (models) => {
    FeaturedExtra.belongsTo(models.extra, {
      foreignKey: {
        name: 'extraIdKey',
        field: 'extra_id',
      },
      targetKey: 'extraId',
      as: 'extra',
    });
  };

  return FeaturedExtra;
};
