// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const GroupExtra = sequelize.define('groupExtra', {
    groupExtraId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    displayOrder: {
      type: DataTypes.INTEGER,
    },
    unfoldedDisplay: {
      type: DataTypes.INTEGER,
    },
    multipleSelection: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    mandatoryGroupValue: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'group_extra',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  GroupExtra.associate = (models) => {
    GroupExtra.belongsTo(models.extraType, {
      foreignKey: {
        name: 'extraTypeIdKey',
        field: 'extra_type_id',
      },
      targetKey: 'extraTypeId',
      as: 'extraType',
    });
    GroupExtra.belongsTo(models.branch, {
      foreignKey: {
        name: 'branchIdKey',
        field: 'branch_id',
      },
      targetKey: 'branchId',
      as: 'branch',
    });
    GroupExtra.belongsTo(models.groupExtraHeader, {
      foreignKey: {
        name: 'groupExtraHeaderIdKey',
        field: 'group_extra_header_id',
      },
      targetKey: 'groupExtraHeaderId',
      as: 'groupExtraHeader',
    });
    GroupExtra.belongsToMany(models.media, {
      through: 'groupExtraMedia',
      foreignKey: 'group_extra_id',
      otherKey: 'media_id',
      as: 'mediaThroughGroupExtraMedias',
    });
    GroupExtra.hasMany(models.extra, {
      foreignKey: {
        name: 'groupExtraIdKey',
        field: 'group_extra_id',
      },
      sourceKey: 'groupExtraId',
      as: 'groupExtraExtras',
    });
    GroupExtra.hasMany(models.extraDetail, {
      foreignKey: {
        name: 'groupExtraIdKey',
        field: 'group_extra_id',
      },
      sourceKey: 'groupExtraId',
      as: 'groupExtraExtraDetails',
    });
    GroupExtra.hasMany(models.groupExtraTranslation, {
      foreignKey: {
        name: 'groupExtraIdKey',
        field: 'group_extra_id',
      },
      sourceKey: 'groupExtraId',
      as: 'groupExtraGroupExtraTranslations',
    });
  };

  return GroupExtra;
};
