// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const LinkedExtra = sequelize.define('linkedExtra', {
    linkedExtraId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    extraId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'linked_extra',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  LinkedExtra.associate = (models) => {
    LinkedExtra.belongsTo(models.extra, {
      foreignKey: {
        name: 'linkedExtraIdKey',
        field: 'linked_extra_id',
      },
      targetKey: 'extraId',
      as: 'linkedExtra',
    });
    LinkedExtra.belongsTo(models.extra, {
      foreignKey: {
        name: 'extraIdKey',
        field: 'extra_id',
      },
      targetKey: 'extraId',
      as: 'extra',
    });
  };

  return LinkedExtra;
};
