// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Period = sequelize.define('period', {
    periodId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    periodLabel: {
      type: DataTypes.STRING,
    },
    periodStart: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    periodDayStart: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    periodMonthStart: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    periodEnd: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    periodDayEnd: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    periodMonthEnd: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'period',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Period.associate = (models) => {
    Period.belongsTo(models.agency, {
      foreignKey: {
        name: 'agencyIdKey',
        field: 'agency_id',
      },
      targetKey: 'agencyId',
      as: 'agency',
    });
    Period.hasMany(models.agencySchedule, {
      foreignKey: {
        name: 'periodIdKey',
        field: 'period_id',
      },
      sourceKey: 'periodId',
      as: 'agencySchedules',
    });
  };

  return Period;
};
