// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Permalink = sequelize.define('permalink', {
    permalinkId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    contentTypeId: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    permalink: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    redirect: {
      type: DataTypes.STRING,
    },
    redirectTypeCode: {
      type: DataTypes.INTEGER,
    },
    state: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    monthDurationStart: {
      type: DataTypes.DATE,
    },
    monthDurationEnd: {
      type: DataTypes.DATE,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'permalink',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Permalink.associate = (models) => {
    Permalink.belongsTo(models.application, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'application_id',
      },
      targetKey: 'applicationId',
      as: 'application',
    });
    Permalink.belongsTo(models.locale, {
      foreignKey: {
        name: 'localeCodeKey',
        field: 'locale_code',
      },
      targetKey: 'localeCode',
      as: 'localeCode',
    });
  };

  return Permalink;
};
