// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const PredefinedValue = sequelize.define('predefinedValue', {
    predefinedValueId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'predefined_value',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  PredefinedValue.associate = (models) => {
    PredefinedValue.belongsTo(models.attribute, {
      foreignKey: {
        name: 'attributeIdKey',
        field: 'attribute_id',
      },
      targetKey: 'attributeId',
      as: 'attribute',
    });
    PredefinedValue.hasMany(models.attributeValue, {
      foreignKey: {
        name: 'predefinedValueIdKey',
        field: 'predefined_value_id',
      },
      sourceKey: 'predefinedValueId',
      as: 'predefinedValueAttributeValues',
    });
    PredefinedValue.hasMany(models.predefinedValueTranslation, {
      foreignKey: {
        name: 'predefinedValueIdKey',
        field: 'predefined_value_id',
      },
      sourceKey: 'predefinedValueId',
      as: 'predefinedValuePredefinedValueTranslations',
    });
  };

  return PredefinedValue;
};
