// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const ProPartner = sequelize.define('proPartner', {
    proPartnerId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    proPartnerEmail: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    proPartnerName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'pro_partner',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  ProPartner.associate = (models) => {
    ProPartner.belongsTo(models.branch, {
      foreignKey: {
        name: 'branchIdKey',
        field: 'branch_id',
      },
      targetKey: 'branchId',
      as: 'branch',
    });
    ProPartner.hasMany(models.booking, {
      foreignKey: {
        name: 'proPartnerIdKey',
        field: 'pro_partner_id',
      },
      sourceKey: 'proPartnerId',
      as: 'proPartnerBookings',
    });
  };

  return ProPartner;
};
