// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RateOneWay = sequelize.define('rateOneWay', {
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    rateOneWayId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    rateOneWayPrice: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
  }, {
    tableName: 'rate_one_way',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  RateOneWay.associate = (models) => {
    RateOneWay.belongsTo(models.agency, {
      foreignKey: {
        name: 'dropOffAgencyIdKey',
        field: 'drop_off_agency_id',
      },
      targetKey: 'agencyId',
      as: 'dropOffAgency',
    });
    RateOneWay.belongsTo(models.agency, {
      foreignKey: {
        name: 'pickupAgencyIdKey',
        field: 'pickup_agency_id',
      },
      targetKey: 'agencyId',
      as: 'pickupAgency',
    });
  };

  return RateOneWay;
};
