// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RateVehicle = sequelize.define('rateVehicle', {
    rateVehicleId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    rateIdErp: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    taxIncluded: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
  }, {
    tableName: 'rate_vehicle',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  RateVehicle.associate = (models) => {
    RateVehicle.belongsTo(models.paymentType, {
      foreignKey: {
        name: 'paymentTypeIdKey',
        field: 'payment_type_id',
      },
      targetKey: 'paymentTypeId',
      as: 'paymentType',
    });
    RateVehicle.hasMany(models.rateVehicleSeason, {
      foreignKey: {
        name: 'rateVehicleIdKey',
        field: 'rate_vehicle_id',
      },
      sourceKey: 'rateVehicleId',
      as: 'rateVehicleRateVehicleSeasons',
    });
  };

  return RateVehicle;
};
