// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RedirectType = sequelize.define('redirectType', {
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    redirectTypeId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    redirectTypeCode: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  }, {
    tableName: 'redirect_type',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  RedirectType.associate = (models) => {
    RedirectType.hasMany(models.redirect, {
      foreignKey: {
        name: 'redirectTypeIdKey',
        field: 'redirect_type_id',
      },
      sourceKey: 'redirectTypeId',
      as: 'redirectTypeRedirects',
    });
  };

  return RedirectType;
};
