// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Redirect = sequelize.define('redirect', {
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    redirectId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    lastUse: {
      type: DataTypes.DATE,
    },
    preserveQuery: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
  }, {
    tableName: 'redirect',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Redirect.associate = (models) => {
    Redirect.belongsTo(models.slug, {
      foreignKey: {
        name: 'sourceSlugIdKey',
        field: 'source_slug_id',
      },
      targetKey: 'slugId',
      as: 'sourceSlug',
    });
    Redirect.belongsTo(models.redirectType, {
      foreignKey: {
        name: 'redirectTypeIdKey',
        field: 'redirect_type_id',
      },
      targetKey: 'redirectTypeId',
      as: 'redirectType',
    });
    Redirect.belongsTo(models.slug, {
      foreignKey: {
        name: 'targetSlugIdKey',
        field: 'target_slug_id',
      },
      targetKey: 'slugId',
      as: 'targetSlug',
    });
  };

  return Redirect;
};
