// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Slug = sequelize.define('slug', {
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    slugId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    contentId: {
      type: DataTypes.STRING,
    },
    slug: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'slug',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Slug.associate = (models) => {
    Slug.belongsTo(models.application, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'application_id',
      },
      targetKey: 'applicationId',
      as: 'application',
    });
    Slug.belongsTo(models.locale, {
      foreignKey: {
        name: 'localeCodeKey',
        field: 'locale_code',
      },
      targetKey: 'localeCode',
      as: 'localeCode',
    });
    Slug.hasMany(models.redirect, {
      foreignKey: {
        name: 'sourceSlugIdKey',
        field: 'source_slug_id',
      },
      sourceKey: 'slugId',
      as: 'sourceSlugRedirects',
    });
    Slug.hasMany(models.redirect, {
      foreignKey: {
        name: 'targetSlugIdKey',
        field: 'target_slug_id',
      },
      sourceKey: 'slugId',
      as: 'targetSlugRedirects',
    });
  };

  return Slug;
};
