// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const TypeRequest = sequelize.define('typeRequest', {
    active: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('CURRENT_TIMESTAMP(6)'),
    },
    typeRequestId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    typeRequestCode: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'type_request',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  TypeRequest.associate = (models) => {
    TypeRequest.belongsTo(models.application, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'application_id',
      },
      targetKey: 'applicationId',
      as: 'application',
    });
    TypeRequest.hasMany(models.typeRequestTranslation, {
      foreignKey: {
        name: 'typeRequestIdKey',
        field: 'type_request_id',
      },
      sourceKey: 'typeRequestId',
      as: 'typeRequestTypeRequestTranslations',
    });
  };

  return TypeRequest;
};
